services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 15s"; python3 ./newsapp
    

  mysql:
    build: ./MySQLDatabase/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306' 